config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments, module: :posts
  end
  resources :user_friends
  devise_for :users
  get 'users', to: 'users#index'
  get 'user_friend', to: 'user_friend#index'
  post 'request_friend', to: 'user_friends#request_friend'
  put 'like_post', to: 'posts#like_post'
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :commentable, polymorphic: true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_friends
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/user_friend.rb
class UserFriend < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'

  scope :find_friends, -> (current_user) { 
    where(friend: current_user, status: 1)
  }

  def can_accept_request?(user)
    status == 0
  end

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = @commentable.comments.new(comment_params)
    @comment.username = current_user
    @comment.save
    redirect_to @commentable, notice: "Your comment was successfully posted."
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts/comments_controller.rb
class Posts::CommentsController < CommentsController
  before_action :set_commentablle


  private
  
    def set_commentablle
      @commentable = Post.find(params[:post_id])
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(user_id: [current_user.id, current_user.user_friends.pluck(:friend_id)])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  def like_post
    post = Post.find(params[:id])
    if post.increment!(:likes_count)
      flash[:notice] = "You liked the post!"
    else
      flash[:alert] = "There was something wrong liking the post"
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.likes_count = 0

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post)
        .permit(:username, :body, :likes_count, :user_id)
        .merge(username: current_user.name, user_id: current_user.id)
    end
end

app/controllers/user_friends_controller.rb
class UserFriendsController < ApplicationController

  def index
    @user_friends = UserFriend.find_friends(current_user)
    @friend_requests = UserFriend.where(friend: current_user, status: 0)
  end

  def request_friend
    friend = User.find(params[:friend])
    friend_request = current_user.user_friends.build(friend_id: friend.id, status: 0)

    if friend_request.save
      flash[:notice] = "Friend Request Sent"
    else
      flash[:alert] = "There was something wrong with the request"
    end
    redirect_to users_path
  end

  def update
    user_friend = UserFriend.find(params[:id])
    # if status is edited to 1, save
    if user_friend.can_accept_request?(current_user) && user_friend.update(status: 1)
      flash[:notice] = "You are now officially friends!"
      current_user.user_friends.create(friend_id: user_friend.user_id, status: 1)
    else
      flash[:alert] = "There was something wrong accepting the friend request"
    end
    redirect_to user_friends_path
  end

  def destroy
    user_friend = UserFriend.find(params[:id])
    other_record = UserFriend.where(user: current_user, friend: user_friend.user).first
    if user_friend.destroy && other_record.destroy
      flash[:notice] = "You are too cool anyway"
    else
      flash[:alert] = "There was something wrong rejecting the friend request"
    end
    redirect_to user_friends_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.where.not(id: current_user.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comments.html.slim
h3 Comments
- commentable.comments.each do |comment|
  div
    = comment.content

app/views/comments/_form.html.slim
= form_for [commentable, Comment.new] do |form|
  div.form-group
    = form.text_area :content, class: "form-control", placeholder: "Add a comment"     
  div class="actions"
    = form.submit

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.slim
h1 Comments

table
  thead
    tr
      th colspan="3"
  tbody
    - @comments.each do |comment|
      tr
        td 
          = link_to 'Show', comment
        td 
          = link_to 'Edit', edit_comment_path(comment)
        td 
          = link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' }

br

= link_to 'New Comment', new_comment_path

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/home/index.html.slim
h1 Welcome to Wannabe Facebook #{current_user.name}

app/views/layouts/_navigation.html.slim
nav
  div
    ul
      li
        = link_to("home", root_path, method: :get)
      li
        = link_to("all users", users_path, method: :get)
      li
        = link_to("timeline", posts_path, method: :get)
      li 
        = link_to("friends", user_friends_path, method: :get)
      li
        = link_to("logout", destroy_user_session_path, method: :delete)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <h1><%= current_user.name if current_user %></h1>
    <%= render 'layouts/navigation' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

  </body>
</html>

app/views/posts/_form.html.slim
= form_with(model: post, local: true) do |form| 
  - if post.errors.any? 
    div id="error_explanation"
      h2
        = pluralize(post.errors.count, "error")
          prohibited this post from being saved

      ul
        - post.errors.full_messages.each do |message|
          li
            = message

  div.field
    = form.label :content
    = form.text_field :content

  div.actions
    = form.submit

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.slim
h1 Posts

table
  thead
    tr
      th Username
      th Body
      th Likes
      th Actions
      th colspan="4"
  tbody
    - @posts.each do |post|
      tr 
        td
          = post.username
        td
          = post.body
        td
          = link_to "#{post.likes_count}", like_post_path(id: post.id), method: :put
        td
          = link_to 'Show', post
    



= link_to 'New Post', new_post_path

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.slim
p
  strong 
    | Username:
  = @post.username

p
  strong 
    | Body:
  = @post.body

p
  strong
    | Likes count:
  = link_to "#{@post.likes_count}", like_post_path(id: @post.id), method: :put

= render partial: "comments/comments", locals: {commentable: @post}
= render partial: "comments/form", locals: {commentable: @post}

= link_to 'Back', posts_path

app/views/user_friends/index.html.slim
h1 This is the User Friend Index Page

h1 Friend List
- if @user_friends
  ul
    - @user_friends.each do |user_friend|
      li
        = user_friend.user.name
        = button_to("Delete", user_friend_path(user_friend), method: :delete)

h1 Friend Requests
- if @friend_requests
  ul
    - @friend_requests.each do |request|
      - if request.can_accept_request?(current_user)
          li
            div
              = request.user.name
              = button_to("Accept", user_friend_path(request), method: :put)   
              = button_to("Deny", user_friend_path(request), method: :delete)

app/views/users/index.html.slim
- @users.each do |user| 
  table
    tr
      th Name
      th Email
      th Actions
      tr
        td  
          = user.name
        td
          = user.email
        td
          - unless current_user.user_friends.pluck(:friend_id).include?(user.id)
            = link_to "Add Friend", request_friend_path(user: current_user, friend: user.id), method: :post

a href="/"
  | Home